import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "../components/Header";
import { ReposProvider } from "@/context/ReposContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "GitHub API",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <ReposProvider>
                <body className={inter.className}>
                    <Header />
                    {children}
                </body>
            </ReposProvider>
        </html>
    );
}
